name: basic_ml_project
channels:
  - defaults
dependencies:
  - ipykernel=5.3.4
  - ipython=7.18.1
  - lxml=4.6.1
  - numpy=1.19.1
  - pandas=1.1.3
  - pip=20.2.4
  - python=3.7
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - ipywidgets=7.5.1
  - click=7.1.2
  - flask=1.1.2
  - pip:
        - -e .  # this will install current project as a package